### ISSUE TITLE
Structure does not allow to easily specify for which ETS the TestTaskResult.xml is

### ISSUE THREAD

**Issue by carmenvandeloo** [inspire-eu-validation/ets-test-resources#1]
With the current structure there is only foreseen to have one TestTaskResult.xml per database. However it is possible that the same database is used to validate different ETSs, for example the same database can be used to validate the au-dc and au-as ETSs. 
It would be good to either :
- keep the first level as a folder per database and then in this create subfolders within the expected_results folder per ETS that can be run on the database; 
- or to create a higher level in the structure with a folder per ETS
- or ...

**Comment by jonherrmann** [comment]
Good point, i think your first suggestion fits best.

Another problem is, that the test logic needs to determine which ETS must to be executed and compared with the predefined result. As our directory structure differs from the ets-repository structure, we should place a property file _test.properties_ in the ETS sub folders which contains information which ETS must be executed, e.g.:

``` properties
ets=inspire/metadata/iso/ets-md-iso-bsxets.xml
```

I will change the Readme and the example.

**Comment by jonherrmann** [comment]
Updated the structure, please check whether example and description are clear.

**Comment by carmenvandeloo** [comment]
I prepared the databases for au, cp and gn today according to the readme. Both the example and description are clear.

Could you give me write access to the repository so I can push the databases I have?

**Comment by jonherrmann** [comment]
According to the repository settings you already should have write access:
https://github.com/interactive-instruments/ets-repository/invitations

**Comment by jonherrmann** [comment]
Was the link for the wrong repo.. use this one:
https://github.com/interactive-instruments/ets-test-resources/invitations
