### ISSUE TITLE
Also store Feature statistics file

### ISSUE THREAD

**Issue by carmenvandeloo** [inspire-eu-validation/ets-test-resources#2]
To be able to verify that the ETS was run on the correct amount of features, the Feature statistics file should be stored as well.

**Comment by cportele** [comment]
It should be stored (as an attachment). Is that not the case for you?

**Comment by carmenvandeloo** [comment]
Yes, indeed. But in the readme of this repository it states nothing about storing this file in it, only the TestTaskResult.xml

**Comment by cportele** [comment]
Ah good point, we need to update this to clarify where to put the attachements. Thanks!

**Comment by carmenvandeloo** [comment]
No problem!
